version: '3'

vars:
  PROJECT_DIR: "$GOPATH/src/github.com/abitofhelp/abohapis"
  PROTO_DIR: "{{.PROJECT_DIR}}/proto"

tasks:
  baz_add_go_module:
    cmds:
      - bazel run @io_bazel_rules_go//go -- get github.com/stretchr/testify@v1.8.4
      - task: gazelle_update_repos
  baz_build_all:
    cmds:
      - bazel build //...
  baz_clean:
    cmds:
      - bazel clean --expunge --async
  baz_list:
    cmds:
      - bazel query //...
  baz_test:
    cmds:
    - bazel test //...

  gazelle_generate_repos:
    cmds:
      - bazel run //:gazelle
  gazelle_update_repos:
    cmds:
      - bazel run //:gazelle-update-repos -- -from_file=go.mod -to_macro=deps.bzl%go_dependencies -prune